### ISSUE TITLE
Offer executable

### ISSUE THREAD

**Issue by fraternl** [sibvic/BadBlocksPlaceholder#1]
Could you also offer a MS-Windows executable if that's possible?
Interested in your solution for a disk I'm having trouble with.

**Comment by sibvic** [comment]
I've created the first release with win7 x64 binaries. Or you can build it using build-win7-x64.bat

**Comment by fraternl** [comment]
It seems such an executable is not without dependencies and needs a lot more including the kitchen sink.

```
  An assembly specified in the application dependencies manifest (BadBlocksPlaceholder.deps.json) was not found:
    package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.1.8'
    path: 'runtimes/win-x64/lib/netcoreapp2.1/Microsoft.CSharp.dll'
```
Looked here, but that just brings on a new quest.
https://www.nuget.org/packages/runtime.win-x64.Microsoft.NETCore.App/2.1.8

**Comment by sibvic** [comment]
> It seems such an executable is not without dependencies and needs a lot more including the kitchen sink.
> 
> ```
>   An assembly specified in the application dependencies manifest (BadBlocksPlaceholder.deps.json) was not found:
>     package: 'runtime.win-x64.Microsoft.NETCore.App', version: '2.1.8'
>     path: 'runtimes/win-x64/lib/netcoreapp2.1/Microsoft.CSharp.dll'
> ```
> Looked here, but that just brings on a new quest.
> https://www.nuget.org/packages/runtime.win-x64.Microsoft.NETCore.App/2.1.8

Do you start it from the publish folder? I've updated the binaries archive to include only one version of the executable (I accidentally included two versions initially).

**Comment by fraternl** [comment]
I was not looking in the right place.
I should have been looking here: https://github.com/sibvic/BadBlocksPlaceholder/releases

I found it. ran it and was able to keep a 4 TB running by marking some bad blocks on it that started to disrupt the whole harddisk when it became full.
Now I may be able to keep it running another year (hopefully)

Many thanks!!!!
